language: python

cache:
  directories:
  - ~/.cache/pip
  - ~/.pyenv

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.2
          env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0"
        - os: linux
          python: 3.3
          env: TOXENV=py33
        - os: linux
          python: 3.4
          env: TOXENV=py34
        - os: linux
          python: 3.5
          env: TOXENV=py35
        - os: linux
          python: 3.5-dev
          env: TOXENV=py35
        - os: linux
          python: nightly
          env: TOXENV=py36
        - os: linux
          python: 3.4
          env: TOXENV=docs
        - os: linux
          python: 2.7
          env: TOXENV=pep8
        - os: linux
          python: 3.4
          env: TOXENV=pep8
        - os: linux
          python: 3.4
          env:
            - TOXENV=packaging
            - PYPIUSER=grzankatest
            #  pypi secured password (PYPIPASS variable), you need to update it to your own if you want to use it
            - secure: "Ioix2P8M6rb4TK+229AMvUBRpaorF4cIp6vCwJeMFG3Yg3BWBCOUF9Sn4FvNhqEz0kPIk0sxDdAIxd1lxEtGc8Tkc2cqpHsEs1KBs1cUC7UiEQwV8AL4EFf3OCXMoBtGS5HW4PwZp1PgN2xwcWbZ7YrGN+JqtFm68KSvxPPLFAKwmFhVxGn11epTOGBKciL5UpS0/rOw0jKsbrq1CmQO2JOVoBSZBnR+55/WL9RFmh5vYNjGahstIAAZLxgNLHqoZHs4LveayYD5WzauOzPh/e/CPGUZDDg4FioJhoFmMMZSg7SbH3Jy8Zxjy7scGlZDzoJ1m99Ih9fm2/9VPZLCsUvXD9y9oxozYcVhlOqEx/B1joL7H76TOWto2lSDoMSB63GMmkyP7Q961YqfkXMQXf6Oe+A+ynH7+Kv9LCxP8wkLmLgUMPVs3wRlp159ftXWSr+PLLJWZ2fF74ujVGFpEtk6AUTWardGmvsXDUoCW1dQ6yu51/Fh/LEP5uqS8SkitcvwMiiL1Uid03R7uhh1mkSYmunJp+utA1HZ6/Z87qs+ee4ghBWvZ88vcOHWmNBJ5/M865cM78BWZv8MozBfTd1rA8fviufj5eu0lc2Oiofu/sFgca8LV7EnKfOcVK2Jb8xKuTM3CPwwJGMa1YFgggamQJcWhEBs6me3z9aLFaY="
        - os: osx
          language: generic
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=py34
        - os: osx
          language: generic
          env: TOXENV=py33
        - os: osx
          language: generic
          env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0"
        - os: osx
          language: generic
          env: TOXENV=py27
#    uncomment and adjust if you want to allow some failures
#    allow_failures:
#        - os: osx
#          language: generic
#          env: TOXENV=py27

# travis-ci runs by default on ancient Ubuntu 12.04 (precise)
# following options will give us Ubuntu 14.04 (trusty)
sudo: required
dist: trusty

before_install:
  - PYTHON_VERSION="py3"
  - if [[ $TOXENV == "py27" ]]; then PYTHON_VERSION="py2" ; fi
  - sudo bash ./install_deps.sh $PYTHON_VERSION

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then travis_wait bash ./.travis/install_linux.sh ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then travis_wait 60 bash ./.travis/install_osx.sh ; fi

# if scipy is used, then installation from pip last longer than 10min, thus we add travis_wait
script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then travis_wait tox --notest && tox -- -n 8 ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then travis_wait bash ./.travis/run_osx.sh ; fi

after_success:
  # deploy to normal if tag is present
  - if [[ $TRAVIS_TAG != "" ]] && [[ $TOXENV == "packaging" ]]; then bash .travis/deploy_package.sh pypi ; fi

notifications:
  email:
    - grzanka@agh.edu.pl
